<b> 1. Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.

In [1]:
x, y = 2, 3

In [2]:
print(x)

2


In [3]:
print(y)

3


In [4]:
del(x)

In [5]:
print(x)

NameError: name 'x' is not defined

<b> 2. Write a line of code that generates the following error:

    NameError: name "x" is not defined


In [6]:
y = 2
c = x + y
print(c)

NameError: name 'x' is not defined

<b> 3. Let x = 10 and y=3. Write a line of code that will make each of the following assignments.

    u=x+y

    v = xy

    w = x/y

    z = sin(x)

    r = 8sin(x)

    s = 5sin(xy)

    p=x**y

In [7]:
x, y = 10, 3

In [8]:
u = x + y
print(u)

13


In [9]:
v = x * y
print(v)

30


In [10]:
w = x / y
print(w)

3.3333333333333335


In [11]:
from math import sin 
z = sin(x)
print(z)

-0.5440211108893698


In [12]:
r = 8*sin(x)
print(r)


-4.352168887114958


In [13]:
s = 5*sin(x*y)
print(s)

-4.940158120464309


In [14]:
p=x**y
print(p)

1000


<b> 4. Show all the variables in the Jupyter notebook after you finish Problem 3.

In [15]:
%whos

Variable   Type                          Data/Info
--------------------------------------------------
p          int                           1000
r          float                         -4.352168887114958
s          float                         -4.940158120464309
sin        builtin_function_or_method    <built-in function sin>
u          int                           13
v          int                           30
w          float                         3.3333333333333335
x          int                           10
y          int                           3
z          float                         -0.5440211108893698


<b> 5. Assign string "123" to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.


In [16]:
S = "123"
N = float(S)
print(type(S))
print(type(N))

<class 'str'>
<class 'float'>


<b> 6. Assign the string "HELLO" to the variable s1 and the string "hello" to the variable s2. Use the ==
operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the
lower method is used on s1. Use the == operator to show that s1 and s2 are equal if upper method
is used on s2.

In [17]:
s1 = "HELLO"
s2 = "hello"
print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

False
True
True


<b> 7. Use the print function to generate the following strings:

    • The world "Engineering" has 11 letters.

    • The word "Book" has 4 letters.

In [18]:
a = "Engineering"
print(a,len(a))

Engineering 11


In [19]:
b = "Book"
print(b,len(b))

Book 4


<b> 8. Check if "Python" is in "Python is great!".


In [20]:
a = "Python is great!"
print("Python" in a)

True


<b> 9. Get the last word "great" from "Python is great!"

In [21]:
a = "Python is great!"
a[10:]

'great!'

<b> 10. Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method. Append 4 to the list_a using the append method.

In [22]:
list_a = [1,8,9,15]
print(list_a)
list_a.insert(1,2)
print(list_a)
list_a.append(4)
print(list_a)

[1, 8, 9, 15]
[1, 2, 8, 9, 15]
[1, 2, 8, 9, 15, 4]


<b> 11. Sort the list_a in problem 10 in ascending order.

In [23]:
list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


<b> 12. Turn "Python is great!" into a list.

In [24]:
word = "Python is great!"
print(word.split())

['Python', 'is', 'great!']


<b> 13. Create one tuple with element "One", 1 and assign it to tuple_a.

In [25]:
tuple_a = ("One",1)

<b> 14. Get the second element in the tuple_a in Problem 13.


In [26]:
tuple_a[-1]

1

<b> 15. Get the unique element from (2, 3, 2, 3, 1, 2, 5).


In [27]:
a = (2,3,2,3,1,2,5)
print(set(a))

{1, 2, 3, 5}


<b> 16. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Obtain the following:

    • union of set_a and set_b

    • intersection of set_a and set_b

    • difference of set_a to set_b using difference method

In [28]:
set_a = set((2,3,2))
set_b = set((1,2,3))

In [29]:
set_a.union(set_b)

{1, 2, 3}

In [30]:
set_a.intersection(set_b)

{2, 3}

In [31]:
set_a.difference(set_b)

set()

<b> 17. Create a dictionary that has the keys "A", "B", "C" with values "a", "b", "c" individually. Print all
the keys in the dictionary.

In [32]:
d = {"A" : "a", "B" : "b", "C": "c"}
d.keys()

dict_keys(['A', 'B', 'C'])

<b> 18. Check if key "B" is in the dictionary defined in Problem 17.


In [33]:
print("B" in d)

True


<b> 19. Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the
assignments from Problem 3.

    u=x+y

    v = xy

    w = x/y

    z = sin(x)

    r = 8sin(x)

    s = 5sin(xy)

    p=x**y

In [34]:
import numpy as np

In [35]:
x = np.array([1,4,3,2,9,4])
y = np.array([2,3,4,1,2,3])

In [36]:
u = x + y
print(u)

[ 3  7  7  3 11  7]


In [37]:
v =  x * y
print(v)

[ 2 12 12  2 18 12]


In [38]:
w = w / y
print(w)

[1.66666667 1.11111111 0.83333333 3.33333333 1.66666667 1.11111111]


In [39]:
from math import sin
z = np.sin(x)
print(z)

[ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ]


In [40]:
r = 8*np.sin(x)
print(r)

[ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996]


In [41]:
s = 5*np.sin(x * y)
print(s)

[ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459]


In [42]:
p = x ** y
print(p)

[ 1 64 81  2 81 64]


<b> 20. Generate an array with size 100 evenly spaced between −10 to 10 using linspace function in
NumPy

In [43]:
a = np.linspace(-10,10,100)
print(a)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

<b> 21. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the
index of the array.

In [44]:
array_a = np.array([-1,0,1,2,0,3])
print(array_a)

[-1  0  1  2  0  3]


In [45]:
a = array_a[array_a > 0]
print(a)

[1 2 3]


<b> 22. Create an array 

    y = (3 5 3)
        (2 2 5)
        (3 8 9)
    
    and calculate its transpose.

In [46]:
y = np.array([[3,5,3],[2,2,5],[3,8,9]])
print(y)

[[3 5 3]
 [2 2 5]
 [3 8 9]]


In [47]:
y.T

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

<b> 23. Create a 2 × 4 zero array.


In [48]:
a = np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<b> 24. Change the second column in the above array to 1.


In [49]:
a[0,1] = 1
print(a)

[[0. 1. 0. 0.]
 [0. 0. 0. 0.]]


<b> 25. Write a magic command to clear all the variables in the Jupyter notebook.

In [51]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [52]:
%whos

Interactive namespace is empty.
